services:
  ubuntu1:
    image: ubuntu:latest
    container_name: ubuntu1
    command: ["bash", "-c", "while true; do sleep 30; done"]
  
  ubuntu2:
    image: ubuntu:latest
    container_name: ubuntu2
    command: ["bash", "-c", "while true; do sleep 30; done"]