services:

  # Load Balancer + Reverse Proxy
  # Upstreams (ato de resolver um pedido de outro server)
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    ports:
      - "443:443"  
    networks:
      - public
      - private

  # Form para operações CRUD
  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    networks:
      - public

  # API com FastAPI
  backend:
    build: ./backend
    networks:
      - private

networks:

  public:
    driver: bridge
    ipam:
      config:
        - subnet: "172.18.0.0/16"

  private:
    driver: bridge
    ipam:
      config:
        - subnet: "172.20.0.0/16"

  
  
