version: '3.8'

services:
  frontend:
    image: nginx:alpine
    container_name: frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    networks:
      app_network:

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      app_network:
        ipv4_address: "172.18.0.2"

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "443:443"
    networks:
      app_network:
        ipv4_address: "172.18.0.3"

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.18.0.0/16"
